### ISSUE TITLE
error while launching action

### ISSUE THREAD

**Issue by lclem** [s-weigand/trigger-mybinder-build#4]
This action worked great for a period, this is my configuration in the relevant .yml file:

name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - master

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: lclem/logic_course
          service-name: gh
          debug: true

Now suddenly it gives the following error (from the actions log):

Run s-weigand/trigger-mybinder-build@v1
https://gke.mybinder.org/build/gh/lclem/logic_course/master
https://ovh.mybinder.org/build/gh/lclem/logic_course/master
BuildServerResponse(https://gke.mybinder.org/build/gh/lclem/logic_course/master): 
Waiting for build to start...

/home/runner/work/_actions/s-weigand/trigger-mybinder-build/v1/dist/index.js:1500
        throw new Error(`${url}\nAn Error occurred requesting a binder build:\n
        ^

Error: https://ovh.mybinder.org/build/gh/lclem/logic_course/master
An Error occurred requesting a binder build:

    undefined
    at EventSource.source.onerror (/home/runner/work/_actions/s-weigand/trigger-mybinder-build/v1/dist/index.js:1500:15)
    at EventSource.emit (events.js:210:5)
    at _emit (/home/runner/work/_actions/s-weigand/trigger-mybinder-build/v1/dist/index.js:336:17)
    at onConnectionClosed (/home/runner/work/_actions/s-weigand/trigger-mybinder-build/v1/dist/index.js:146:5)
    at ClientRequest.<anonymous> (/home/runner/work/_actions/s-weigand/trigger-mybinder-build/v1/dist/index.js:325:7)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

**Comment by s-weigand** [comment]
Looks like the ovh server is down. 
I will change the code to add the `gesis` and `turing` servers, and only throw an error when all fail.
When only some fail it should only log the error.

**Comment by s-weigand** [comment]
It should work again.

**Comment by lclem** [comment]
it does, many thanks for taking care of this!
